### ISSUE TITLE
Procedural macro reimplementation of `quote!` to resolve longstanding limitations

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/request-for-implementation#8]
Originally filed as https://github.com/dtolnay/quote/issues/82 but I would like this to begin its life as a separate library.

The current macro_rules-based quote macro has the limitation that duplicate interpolations inside of a repetition are not allowed. `quote! { #a #a }` works but `quote! { #(#a #a)* }` does not work. The reason boils down to macro_rules macros having no way to determine that two identifiers are equal.

Some background on the quote macro:

- `quote! { #a #a }` expands to:

    ```rust
    {
        let mut _s = TokenStream::new();
        let _span = Span::call_site();
        ToTokens::to_tokens(&a, &mut _s);
        ToTokens::to_tokens(&a, &mut _s);
        _s
    }
    ```

- `quote! { #(#a)* }` expands to:

    ```rust
    {
        let mut _s = TokenStream::new();
        let _span = Span::call_site();
        for a in a {
            ToTokens::to_tokens(&a, &mut _s);
        }
        _s
    }
    ```

- `quote! { #(#a #b)* }` expands to:

    ```rust
    {
        let mut _s = TokenStream::new();
        let _span = Span::call_site();
        for (a, b) in a.into_iter().zip(b) {
            ToTokens::to_tokens(&a, &mut _s);
            ToTokens::to_tokens(&b, &mut _s);
        }
        _s
    }
    ```

- `quote! { #(#a #a)* }` expands to:

    ```rust
    {
        let mut _s = TokenStream::new();
        let _span = Span::call_site();
        for (a, a) in a.into_iter().zip(a) {
            ToTokens::to_tokens(&a, &mut _s);
            ToTokens::to_tokens(&a, &mut _s);
        }
        _s
    }
    ```

That last expansion is illegal so the quote invocation fails.

```console
error[E0416]: identifier `a` is bound more than once in the same pattern
  --> src/main.rs:12:17
   |
12 |         for (a, a) in a.into_iter().zip(a) {
   |                 ^ used in a pattern more than once
```

In an implementation as a procedural macro we would want that invocation to expand instead as:

```rust
{
    let mut _s = TokenStream::new();
    let _span = Span::call_site();
    for a in a {
        ToTokens::to_tokens(&a, &mut _s);
        ToTokens::to_tokens(&a, &mut _s);
    }
    _s
}
```

**Comment by Goncalerta** [comment]
I created the repository [proc-quote](https://github.com/Goncalerta/proc-quote) in order to work on this new library.

**Comment by Goncalerta** [comment]
Besides the already existent `#ident` and `#( #iter )*` patterns, I'm adding a new one in my crate: `#{ expr }`.

I created this because sometimes I feel the need to call a function or access an inner element of a struct inside `quote!`, which is not normally allowed. This means I'd need to create a new variable outside the macro just to use it inside. 

With `#{ my_struct.inner }` or `#{ call_function() }` this issue is solved. The `#{ ... }` pattern accepts any block of code that evaluates to `ToTokens`, even though it is supposed to be used in simpler cases, whereas more complex ones it can still be done outside the macro.

@dtolnay what are your thoughts on this feature?

**Comment by dtolnay** [comment]
I strongly prefer not to have that feature and I believe the library is worse off for providing it.

Some existing discussion in https://github.com/dtolnay/quote/pull/88 and numerous other threads on the quote repo.

**Comment by Goncalerta** [comment]
I'm sorry, it was silly on my part not to check if this had been proposed before. It seemed such a simple and straightforward addition that I felt compelled to add it.

Thanks for pointing me to the existing discussion. I will remove this functionality from my crate.

**Comment by dtolnay** [comment]
Thanks! To be clear, plenty of people think I am wrong on this.

Let me know once your existing TODO items are either implemented or have issues filed to track them, and the crate has been published to crates.io, and then we can close out this thread and mark it off the list. :)

**Comment by eddyb** [comment]
For the record, [this is implementation of the (unstable) `proc_macro::quote!`](https://github.com/rust-lang/rust/blob/74256630117fedf479edbd1145cac47c88036aec/src/libproc_macro/quote.rs).

It's very simple, but it could be used as a starting point for someone else.

However, it can't just be copied verbatim to a proc macro, as it uses the unstable `Span::def_site()` *and* it relies on a different part of the compiler special-casing `proc_macro::quote!` so that the paths it generates resolve in `proc_macro`.

**Comment by Goncalerta** [comment]
It is up! https://crates.io/crates/proc-quote

:)

**Comment by james-darkfox** [comment]
If proc-quote is slower than quote, we don't need proc-quote. We need to just fix quote. If the only thing blocking this is the incorrect assumption that `macro_rules` cannot filter out duplicates, here you go.

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=0bb9df8fd1d555d84c1720e66f8a044b

```rust
macro_rules! tt_match {
    ($left:tt in
        $( ($($right:tt)|*) => $cb:tt!$cba:tt );+
        $(; _ => $de:tt!$fault:tt)?
        $(;)?
    ) => {{
        macro_rules! __tt_match_internal {
            $( $( ($right) => { $cb!$cba }; )* )+
            $( ($left) => { $de!$fault } )*
        }
        __tt_match_internal!{ $left }
    }}
}

macro_rules! uniq {
    (($($xs:tt)*) () $cb:tt!($($tt:tt)*)) => {
        $cb!( $($tt:tt)* $($xs)* )
    };

    (($($xs:tt)*) ($y:tt $($ys:tt)*) $cb:tt!$cba:tt) => {
        tt_match!{
            $y in
                ($($xs)|*) => uniq!(($($xs)*) ($($ys)*) $cb!$cba);
                _ => uniq!(($($xs)* $y) ($($ys)*) $cb!$cba);
        }
    };
}

fn main() {
    println!("{}", uniq!(() (a a b c c) stringify!()));
}
```
